### ISSUE TITLE
TODO (feature requests list)

### ISSUE THREAD

**Issue by ghost** [oskardolch/SteamCAD#3]
Here is short list of feature requests (that could be extended later):

- General tasks:
  - [ ] add application icon (`steamcad.png`, `steamcad.svg`, etc.) & desktop file (`steamcad.desktop`) for Linux;
  - [ ] add instruction on localizing UI;
  - [ ] add instruction on translating «SteamCAD Manual»;
  - [ ] ...
- New features:
  - [ ] add *"About"* dialog into the UI as menu entry *"About"*;
  - [ ] add *"Show snapping grid"* as an option (as menu entry "View -> Snapping grid" and as option in "Properties");
  - [ ] add *"Import reference image"* as background (`*.png`, `*.gif`, etc.);
  - [ ] ...

NOTE: I'm interested in *SteamCAD* improvement, so now test *SteamCAD* and later ***will*** help you with those tasks (via pull requests) that I could solve!

**Comment by oskardolch** [comment]
Great, I want to keep SteamCAD as small as possible, not to let it grow in the functionality to beasts like Gimp or many other software, but the changes you suggest seem to be reasonable. Icons would be definitively welcome, regarding localization, the Windows version is quite prepared for it, the Linux version would require more attention, although all the strings in the code should be prepared for i18n. Can you suggest a place where to put notes about it?

**Comment by ghost** [comment]
> Can you suggest a place where to put notes about it?

Think, i18n notes should be placed in `TRANSLATION.md` and/or `CONTRIBUTING.md` file(s) into the root of `master` branch or into the `docs` subfolder. For exapmle:

- https://github.com/jimevins/glabels-qt/tree/master/docs

**Comment by oskardolch** [comment]
Hi, I have added the GNU build, including gettext support. So the Linux version can be localized now by translating the po/SteamCAD.pot and saved as <lang_code>.po

**Comment by Andres6936** [comment]
What do you think about using XML to save translations?

In my opinion it is easier to use a structure like this: [Spanish Latin](https://github.com/Ludeon/RimWorld-SpanishLatin) for translations.

**Comment by oskardolch** [comment]
Well, first of all, I tried to make the program as simple as possible, so basically it does not need translation at all. I suppose the potential users should know what they do, which requires some level of education where minimum knowledge of English, needed to work with the application, is expected. But, if anybody feels like they would like to bring the application to even broader audience, then I would prefer using the native translation means, which is resource files on Windows and GNU i18n on Linux. However, since it is open source software, you are welcome to fork it and make any enhancements you like.
